<a href="https://colab.research.google.com/github/JordanDCunha/On-Complexity/blob/main/Chapter7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 7.1 Introduction


A **cellular automaton (CA)** is a model of a world with very simple physics.  
The term *cellular* means that the world is divided into discrete chunks, called **cells**.


An **automaton** is a machine that performs computations. This machine could be a physical device, but more often it is a **mathematical abstraction** or a **computer simulation**.


This chapter presents experiments conducted by **Stephen Wolfram** in the 1980s, demonstrating that some cellular automata exhibit **surprisingly complex behavior**, including the ability to perform **arbitrary computations**.


The chapter also discusses the implications of these results, and concludes by suggesting methods for **efficiently implementing cellular automata in Python**.


The code for this chapter is provided in **chap07.ipynb** in the repository for this book.  
More information about working with the code can be found in **Section 1.4**.


## 7.2 A Simple CA


Cellular automata are governed by **rules** that determine how the state of cells changes over time.


As a trivial example, consider a cellular automaton (CA) with a **single cell**.  
The state of the cell at time step *t* is an integer value.


As an initial condition, suppose the state of the cell starts at **0**.


Now we need a rule. Arbitrarily, we choose a rule where the state increases by **1 at each time step**.


This CA performs a very simple computation: **it counts**.


However, this CA is atypical. Most cellular automata have a **finite number of possible states**.


For example, suppose a cell can only have **two states**, 0 or 1.


For a 2-state CA, we could define a rule where the next state is the current state plus one, **modulo 2**.


The behavior of this CA is simple: it **blinks**.  
The state alternates between 0 and 1 at each time step.


Most cellular automata are **deterministic**, meaning that given the same initial state, they always produce the same result.


Some cellular automata are **nondeterministic**, meaning their rules include randomness.  
We will see examples of these later.


The CA in this section has only one cell, so it can be considered **zero-dimensional**.


In the rest of this chapter, we explore **one-dimensional (1-D) cellular automata**, and in the next chapter we explore **two-dimensional CAs**.


## 7.3 Wolfram’s Experiment

### Background
- In the early 1980s, Stephen Wolfram conducted a systematic study of **one-dimensional cellular automata (1-D CAs)**.
- He identified **four categories of behavior**, ranging from simple to highly complex.

### Lattice Structure
- Cells are arranged in a **1-D lattice**.
- Each cell is connected to **two neighbors** (left and right).
- The lattice can be:
  - Finite
  - Infinite
  - Arranged in a ring

### Neighborhood Definition
- Wolfram used a **3-cell neighborhood**:
  - The cell itself
  - Its left neighbor
  - Its right neighbor
- The neighborhood determines the **next state** of the center cell.

### Cell States
- Each cell has **two possible states**:
  - `0` (off)
  - `1` (on)

### Rule Tables
- A rule is defined by a table mapping:
  - Each possible neighborhood state (3-bit pattern)
  - To the next state of the center cell
- There are **8 possible neighborhood configurations**.

### Rule Encoding
- Wolfram encodes rules by reading the output row as a **binary number**.
- Example:
  - Binary: `00110010`
  - Decimal: `50`
- This rule is called **Rule 50**.

### System Evolution
- The first row represents the **initial state**:
  - One cell is “on”
  - All others are “off”
- Each subsequent row represents the **next time step**.

### Triangle of Influence
- The triangular shape seen in CA diagrams is a result of:
  - Local interactions
  - Finite propagation speed
- Each cell influences:
  - One neighbor per time step in each direction
- Over time, this creates a **triangle of influence** showing which future cells can be affected.

### Key Takeaway
- Simple local rules in cellular automata can produce **structured and sometimes complex global behavior**.


## 7.4 Classifying Cellular Automata (CAs)

### How Many CAs Are There?
- Each cell has **two possible states**: on (1) or off (0).
- A **3-cell neighborhood** has:
  - \( 2^3 = 8 \) possible configurations.
- A rule table assigns:
  - One output bit for each configuration.
- Therefore:
  - Each rule is defined by **8 bits**.
  - Total possible rules: **256**.

### Wolfram’s Experiment
- Stephen Wolfram tested **all 256 rules**.
- He visually examined their behavior over time.
- Based on observed patterns, he proposed **four classes** of cellular automata.

### Class 1: Uniform Behavior
- Simplest and least interesting class.
- From almost any initial state, the CA evolves to:
  - A **uniform pattern** (all cells the same).
- Example:
  - **Rule 0** → always produces an empty pattern after one step.

### Class 2: Simple Structured Behavior
- Produces **simple, stable, or repeating patterns**.
- Often shows **nested or self-similar structure**.
- Example:
  - **Rule 50** → generates nested patterns.
  - **Rule 18** → shows especially clear nested structure (see Figure 7.2 after 64 steps).
- Patterns can be intricate and visually appealing.
- Still considered **relatively simple** compared to later classes.

### Relative Complexity of Classes
- **Class 1**: Very simple (uniform outcomes).
- **Class 2**: Simple but structured (nested patterns).
- **Classes 3 and 4**:
  - More complex
  - More dynamic
  - More interesting for computation and unpredictability.

### Key Takeaways
- Wolfram identified **four classes** of CA behavior.
- **Class 1 and Class 2** are considered **relatively simple**.
- This classification helped frame later discussions about complexity and computation in CAs.


## 7.5 Randomness in Cellular Automata

### Class 3 Cellular Automata
- **Class 3** CAs generate behavior that appears **random**.
- Example:
  - **Rule 30** (shown after 100 time steps in Figure 7.3).
- Visual characteristics:
  - Left side shows some apparent pattern.
  - Right side contains triangles of varying sizes.
  - The **center region appears highly random**.

### Rule 30 and Randomness
- If you take the **center column** of Rule 30 over time:
  - Treat it as a sequence of bits.
  - It is difficult to distinguish from a truly random sequence.
- This sequence passes many **statistical randomness tests**.
- Because of this, Rule 30 has been used as a source of randomness in practice.

### Pseudo-Random Number Generators (PRNGs)
- Programs that generate random-seeming numbers are called **pseudo-random number generators**.
- They are **not truly random**, for several reasons.

### Why PRNGs Are Not Truly Random
- **Deterministic process**:
  - Given the same initial state, they always produce the same sequence.
- **Detectable regularities**:
  - Some PRNGs show statistical patterns (e.g., early C `rand` implementations).
- **Finite state**:
  - Any PRNG with limited memory will eventually **repeat**.
  - The length before repetition is called the **period**.
- **Not based on fundamentally random physical processes**:
  - Unlike radioactive decay or thermal noise.

### Modern View of PRNGs
- Modern PRNGs:
  - Are statistically indistinguishable from random for most uses.
  - Have periods so long they are effectively infinite for practical purposes.
- This raises a philosophical question:
  - Is there a real difference between high-quality pseudo-randomness and “true” randomness?
- Wolfram argues **there is no meaningful difference** (A New Kind of Science, pp. 315–326).

### Key Takeaways
- Class 3 CAs can generate behavior that looks random.
- Rule 30 is a classic example of computational randomness.
- PRNGs are deterministic and finite, but can still be extremely effective.
- The boundary between “true” randomness and pseudo-randomness is not always clear.


## 7.6 Determinism

### Why Class 3 CAs Are Surprising
- Class 3 cellular automata generate **apparently random behavior**.
- This is surprising because CAs are:
  - Simple
  - Fully deterministic
- Their behavior challenges traditional views of **determinism**.

### Philosophical Determinism
- Determinism comes in **many strengths**, ranging from weak to strong.
- The text presents four positions, ordered from least to most extreme.

### Levels of Determinism
- **D1**: Deterministic models can make accurate predictions for *some* physical systems.
- **D2**: Many systems are deterministic, but some are intrinsically random.
- **D3**: All events are caused by prior events, but many systems are fundamentally unpredictable.
- **D4**: All events are caused by prior events and are, in principle, predictable.

### Purpose of the Spectrum
- D1 is weak enough that almost everyone accepts it.
- D4 is strong enough that almost no one accepts it.
- The middle positions reflect views held by many scientists and philosophers.
- Public opinion has shifted along this spectrum over time.

### Historical Shifts in Determinism
- **Before the scientific revolution**:
  - The universe was seen as unpredictable or controlled by supernatural forces.
- **After Newtonian mechanics**:
  - Some believed in near-complete predictability (close to D4).
- **Laplace’s Demon (1814)**:
  - Hypothetical intellect that knows all forces and positions.
  - Could predict the entire future and past of the universe.
  - Symbolizes extreme determinism.

### Challenges to Strong Determinism
- **Thermodynamics** introduced irreversibility.
- **Radioactivity** introduced randomness.
- **Quantum mechanics** challenged causality and predictability.
- **Chaos theory (1960s)** showed:
  - Deterministic systems can be unpredictable.
  - Small errors in initial conditions grow rapidly.
  - Prediction is limited to short time scales.

### Why Cellular Automata Are Especially Disturbing
- Chaotic systems are usually:
  - Continuous
  - Nonlinear
- Cellular automata are:
  - Discrete
  - Simple
  - Rule-based
- Yet they still produce complex, unpredictable behavior.
- This makes Wolfram’s results more surprising to deterministic worldviews.

### Determinism and Free Will
- A long-standing objection to determinism is its conflict with **human free will**.
- Complexity science may offer a way to reconcile:
  - Deterministic rules
  - Emergent, unpredictable behavior
- This topic will be revisited later (Section 12.7).

### Key Takeaways
- Determinism exists on a spectrum, not as a single idea.
- Scientific discoveries have steadily weakened strong determinism.
- Simple deterministic systems can still be unpredictable.
- Cellular automata challenge our intuition about cause, prediction, and control.


## 7.7 Spaceships (Class 4 Cellular Automata)

### Class 4 Behavior
- Class 4 cellular automata show the **most complex and surprising behavior**.
- Some 1-D CAs, especially **Rule 110**, are **Turing complete**.
- **Turing complete / Universal** means:
  - The system can compute **any computable function**
- This property was **proved by Matthew Cook in 1998**.

### Rule 110 at Small Scale
- When starting from:
  - A single active cell
  - 100 time steps
- The behavior appears:
  - Partly regular
  - Partly chaotic
- At this scale, nothing obviously special stands out.

### Rule 110 at Larger Scale
- With:
  - Random initial conditions
  - 600 time steps
- More structure becomes visible:
  - After ~100 steps, the background settles into a **repeating pattern**
  - Persistent structures emerge as **disturbances in the background**

### Spaceships
- These persistent structures are called **spaceships**.
- Types of spaceships:
  - **Stationary** → appear as vertical lines
  - **Moving** → appear as diagonal lines
- The slope of a diagonal indicates:
  - How many time steps it takes to move one column

### Interactions and Collisions
- Spaceships can **collide** with each other.
- Outcomes depend on:
  - Types of spaceships
  - Their phase at collision
- Possible collision results:
  - Both ships annihilate
  - One ship survives unchanged
  - New ships are created

### Computation in Rule 110
- Spaceships act like **signals** moving through space.
- Collisions act like **logic gates**:
  - AND
  - OR
  - Other logical operations
- This signal-and-collision mechanism enables **computation**.

### Key Takeaways
- Rule 110 is a simple, deterministic system with:
  - Emergent structure
  - Persistent moving objects
  - Computational universality
- Complex computation can arise from:
  - Very simple rules
  - Local interactions
- This makes Class 4 CAs central to complexity science.


## 7.8 Universality

### Computability Theory
- **Computability theory** studies:
  - Models of computation
  - What functions can (and cannot) be computed
- It asks fundamental questions about:
  - The limits of computation
  - What it means for a process to be “computable”

### Turing Machines
- Proposed by **Alan Turing (1936)**
- A Turing machine is:
  - A **1-D cellular automaton**
  - Infinite in both directions
  - Equipped with a **read–write head**
- Components:
  - A tape of cells (usually binary)
  - A head that:
    - Reads a cell
    - Writes a new value
    - Moves left or right
  - A **finite set of internal states**
  - A **rule table** mapping:
    - (machine state, cell state) → action

### Why Turing Machines Matter
- Not practical computers, but:
  - They model real computer architectures
- Any real program can be:
  - Simulated by a Turing machine (in principle)
- Turing showed it is possible to:
  - Precisely characterize the set of functions a Turing machine can compute
- These functions are called **Turing-computable**

### Turing Completeness
- A system is **Turing complete** if:
  - It can compute any Turing-computable function
- Many very different models are Turing complete:
  - Turing machines
  - Lambda calculus
  - Modern programming languages
- This equivalence is surprising because:
  - The models look radically different

### Church–Turing Thesis
- Claim:
  - All reasonable definitions of computation capture the same fundamental concept
- Implication:
  - Different computational models are equivalent in power
- Computability is:
  - Independent of specific hardware or representation

### Rule 110 and Universality
- **Rule 110** is:
  - A very simple 1-D cellular automaton
  - Yet **Turing complete**
- This is remarkable because:
  - The rules are extremely simple
  - The behavior emerges from local interactions
- Rule 110 supports:
  - The Church–Turing Thesis

### Principle of Computational Equivalence (Wolfram)
- Stated in *A New Kind of Science*
- Claims:
  - Almost all non-trivially simple systems perform computations
  - Most systems reach **maximal computational power**
  - Therefore, most systems are **computationally equivalent**
- Applied to CAs:
  - Class 1 & 2 → obviously simple
  - Class 3 → randomness (simple in a different sense)
  - **Class 4 → true complexity and universality**

### Big Picture
- Universality can emerge from:
  - Extremely simple rules
  - Deterministic local interactions
- Complex computation does not require:
  - Complex design
- This challenges traditional views of:
  - Complexity
  - Computation
  - Determinism


## 7.9 Falsifiability

### Wolfram’s Claim vs. Church–Turing
- Wolfram argues his **Principle of Computational Equivalence** is stronger than the Church–Turing Thesis because:
  - It applies to **natural systems**, not just abstract models
- Criticism:
  - Saying natural processes “can be viewed as computations” may reflect:
    - A **theoretical perspective**
    - Not a testable claim about the physical world

### The Problem of Falsifiability
- Wolfram’s principle includes vague qualifiers like:
  - “almost”
  - “obviously simple”
- These undefined terms may make the principle:
  - **Unfalsifiable**

### What Is Falsifiability?
- Introduced by **Karl Popper**
- A hypothesis is **falsifiable** if:
  - There exists a realistic experiment or observation
  - That could prove it false
- Falsifiability is a key criterion separating:
  - Science
  - Pseudoscience

### Example of a Falsifiable Hypothesis
- **Universal common descent**:
  - All life on Earth descends from a common ancestor
- It makes testable predictions:
  - Genetic similarities across species
- A discovery of a species with radically different DNA:
  - Would challenge or contradict the theory

### Example of an Unfalsifiable Hypothesis
- **Special creation**:
  - Species were created in their current form by a supernatural agent
- It is unfalsifiable because:
  - Any observation can be explained as the creator’s will
  - No possible evidence could contradict it

### Why Unfalsifiable Hypotheses Are a Problem
- They can be appealing because:
  - They cannot be proven wrong
- But they are scientifically useless because:
  - They make no predictions
  - They have no practical consequences

### Science vs. Belief
- The goal of science is:
  - Making reliable predictions
  - Understanding and acting in the world
- Unfalsifiable theories:
  - Do not guide research
  - Do not inform applications or experiments

### Key Takeaway
- A hypothesis without falsifiable consequences:
  - Cannot advance scientific understanding
- This raises doubts about whether Wolfram’s principle:
  - Is a scientific claim
  - Or a philosophical viewpoint


## 7.10 What Is This a Model Of?

### Cellular Automata as Models
- Some cellular automata (CAs) are mainly:
  - Mathematical objects
  - Interesting because they are surprising, useful, or visually appealing
- Others contribute to theory:
  - e.g., the Church–Turing thesis
- However, it is often unclear whether CAs are:
  - Models of real physical systems
  - Or purely abstract constructions

### Abstraction and Physical Realism
- If CAs model physical systems, they are:
  - Highly abstract
  - Lacking detailed realism
- Example:
  - Cone snail shell patterns resemble CA patterns
  - This suggests CAs might model shell growth mechanisms
- Problem:
  - It’s unclear how CA components map to real biology:
    - CA cells ↔ biological cells?
    - Neighbor communication ↔ chemical signals?
    - Rules ↔ protein interaction networks?

### Realistic Models: Strengths and Limits
- In traditional physical modeling:
  - Greater realism is usually seen as a strength
  - Clear correspondence between model elements and real elements
- Benefits:
  - Better predictions
  - More convincing explanations
- Limits:
  - Highly detailed models become:
    - Harder to analyze
    - Computationally expensive
  - At extreme complexity:
    - Direct experimentation may be easier than modeling

### The Power of Simple Models
- Simple models can be compelling because:
  - They isolate essential mechanisms
  - They are easier to understand and analyze
- They offer a **different kind of explanation** than detailed models

### Explanation via Detailed Models
- Typical logic of detailed modeling:
  - Build a realistic model of system A
  - Show model behavior B matches observed behavior
  - Explain B by tracing causal mechanisms within the model
- This relies on:
  - Strong similarity between model and real system

### Explanation via Simple Models
- Simple models do **not** claim realism
- Instead, they argue:
  - A class of models shares certain features
  - Any mod


## 7.11 Implementing Cellular Automata (CAs)

### Overview
- This section explains how 1-D cellular automata are implemented in Python
- The figures in the chapter are generated using:
  - `Cell1D`: represents the CA
  - `Cell1DViewer`: visualizes the CA
- Internally, the CA state is stored as a **NumPy array**:
  - Columns → cells
  - Rows → time steps

### Example CA: Parity Rule
- This example CA computes **parity** for each neighborhood
- Parity definition:
  - `0` if the sum is even
  - `1` if the sum is odd


In [1]:
import numpy as np

rows = 5
cols = 11
array = np.zeros((rows, cols), dtype=np.uint8)

# Set initial condition: a single 1 in the center
array[0, 5] = 1

print(array)


[[0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


### Data Representation
- The CA state is stored in a 2-D NumPy array
- `dtype=np.uint8` means:
  - Unsigned 8-bit integers
  - Efficient storage for binary states (0 or 1)
- Only the first row is initialized
- All future rows will be computed by the CA rule


In [ ]:
array.shape


### Visualizing the CA
- The CA is displayed as an image:
  - Each cell is a colored square
- The `Blues` colormap is used:
  - Dark blue → cell is on (1)
  - Light blue → cell is off (0)
- No interpolation ensures sharp cell boundaries


In [ ]:
import matplotlib.pyplot as plt

def plot_ca(array, rows, cols):
    cmap = plt.get_cmap('Blues')
    plt.imshow(array, cmap=cmap, interpolation='none')
    plt.xlabel("Cells")
    plt.ylabel("Time steps")


### Computing the Next Time Step
- Each new row depends on the previous row
- For each cell:
  - Select the cell and its two neighbors
  - Compute the sum
  - Take parity using modulus (`% 2`)
- This example uses a **finite lattice**


In [ ]:
def step(array, i):
    rows, cols = array.shape
    row = array[i - 1]

    for j in range(1, cols - 1):
        elts = row[j - 1:j + 2]
        array[i, j] = sum(elts) % 2


### Boundary Conditions
- The first and last cells have only one neighbor
- To simplify the implementation:
  - Boundary cells are **never updated**
  - They remain 0 for all time steps
- This avoids special-case logic for edges


In [ ]:
# Run the CA for all time steps
for i in range(1, rows):
    step(array, i)

plot_ca(array, rows, cols)
plt.show()


### Key Takeaways
- A 1-D CA can be implemented using:
  - A 2-D NumPy array
  - Simple slicing and arithmetic
- Visualization treats the array as an image
- Even very simple rules (like parity) can generate structure
- Boundary handling is a design choice that affects behavior


## 7.12 Cross-Correlation

### Big Idea
- The operation used in the previous section—selecting neighboring elements and summing them—is called **cross-correlation**
- Cross-correlation is widely used in:
  - Signal processing
  - Image processing
  - Time series analysis
  - Cellular automata
- NumPy provides an optimized function for this: `np.correlate`

---

### Definition of Cross-Correlation
- Given:
  - An array `a`
  - A window `w` of length `N`
- The cross-correlation result `c` is defined as:

  $$
  c_k = \sum a[k : k+N] \cdot w
  $$

- In Python, a single element can be computed as:

```python
def c_k(a, w, k):
    N = len(w)
    return sum(a[k:k+N] * w)


In [ ]:
row = np.arange(10, dtype=np.uint8)
# [0 1 2 3 4 5 6 7 8 9]


In [ ]:
window = [1, 1, 1]


In [ ]:
def correlate(row, window):
    cols = len(row)
    N = len(window)
    c = [c_k(row, window, k) for k in range(cols - N + 1)]
    return np.array(c)


In [ ]:
np.correlate(row, window, mode='valid')


In [ ]:
np.correlate(row, window, mode='same')


In [ ]:
def step2(array, i, window=[1, 1, 1]):
    row = array[i - 1]
    c = np.correlate(row, window, mode='same')
    array[i] = c % 2


## 7.13 CA Tables

- The earlier CA implementation works only for **totalistic** rules  
  - Totalistic rules depend **only on the sum** of neighboring cells  
  - Example: neighborhoods `100` and `001` have the same sum but may behave differently in many CAs

- Most cellular automata depend on **which neighbors are on/off**, not just the sum

- To support general rules:
  - Interpret each 3-cell neighborhood as a **binary number**
  - Use weights `[4, 2, 1]` to encode the neighborhood
    - `111 → 7`
    - `100 → 4`
    - `001 → 1`
  - Use this value as an **index into a rule table**


In [ ]:
def step3(array, i, window=[4, 2, 1]):
    row = array[i-1]
    c = np.correlate(row, window, mode='same')
    array[i] = table[c]


### Rule Tables

- A **rule table** maps each possible neighborhood (0–7) to the next cell state
- Rules are encoded as integers between **0 and 255**
  - Each rule corresponds to an **8-bit binary number**
  - Each bit specifies the output for one neighborhood configuration

- NumPy’s `unpackbits` is used to convert the rule number into its binary form
- The table is reversed so indices match neighborhood values correctly


In [ ]:
def make_table(rule):
    rule = np.array([rule], dtype=np.uint8)
    table = np.unpackbits(rule)[::-1]
    return table

# Example: Rule 150
table = make_table(150)
print(table)


- The resulting table contains 8 values (for neighborhoods 0–7)
- This logic is encapsulated in the **Cell1D** class in `Cell1D.py`
- Using rule tables allows implementation of **any elementary 1-D cellular automaton**


## 7.15 Glossary

- **Cellular Automaton (CA)**
  - A computational model with very simple rules and structure
  - The world is divided into discrete units called *cells*
  - An *automaton* performs computations via mathematical rules or simulations

- **Church–Turing Thesis**
  - The claim that all reasonable models of computation capture the same fundamental notion of computability
  - Computability is independent of the specific computational model used

- **Cross-Correlation**
  - An operation that selects overlapping elements from an array and combines them (typically by summation)
  - Widely used in signal processing, statistics, and cellular automata

- **Falsifiability**
  - A property of a scientific hypothesis
  - A hypothesis is falsifiable if an experiment could, in principle, show it to be false

- **Pseudo-Random Number Generators (PRNGs)**
  - Deterministic programs that generate sequences that appear random
  - Not truly random because they rely on algorithms and finite internal state

- **Turing Complete (Universality)**
  - A system is Turing complete if it can compute any computable function
  - Indicates maximal computational power

- **Unfalsifiable**
  - A hypothesis that cannot be tested in a way that could contradict it
  - Considered scientifically unhelpful because it makes no testable predictions
